### ISSUE TITLE
hide Notifications

### ISSUE THREAD

**Issue by Urkman** [dkcas11/CRNotifications#24]
Is there a way to hide Notifications?
When I open one with dismissDelay = 0 it stays open. How can I hide this?

**Comment by dkcas11** [comment]
I think there was a method of hiding it at some point. But basically, whenever you use `0` it wont hide unless you tap the notification.

Calling `CRnotifications.show....` could return the notification that will be displayed, which in turn can expose the `hide` method. Multiple notifications can be displayed over eachother, so that way you can keep track of every single one if needed (al though i don't see where this is useful).
I think that would be better than having a `hide` method on `CRNotifications` at least.

What is the use case for hiding it in ways other than the user tapping?

**Comment by Urkman** [comment]
I show a notification, when a background task is running. I this case, when a new route is being calculated. And the notification should stay there until the task is finished...

**Comment by dkcas11** [comment]
Ah I see. 
How do you like my proposal, of returning the notification? That should make it easy to manage.

**Comment by dkcas11** [comment]
Checkout this branch that includes the feature: https://github.com/dkcas11/CRNotifications/tree/dev/hide
Let me know how it works and I will merge it into master.

**Comment by dkcas11** [comment]
This is now in master.
