### ISSUE TITLE
issue when i try present  CRNotifications

### ISSUE THREAD

**Issue by adelbios** [dkcas11/CRNotifications#3]
u've issue when i try display CRNotifications 

in this class CRNotifications  

UIApplication.shared.keyWindow?.rootViewController.view.addSubview(view)
 but i fix it ..... 
 
adding parms   <viewController : UIViewController> 
showNotification(type: CRNotificationType, title: String, message: String, dismissDelay: Int , viewController : UIViewController )

because when i try implement pushView controller or segue 
the  CRNotifications Displayed in the previous VC 

so...  viewController.view.addSubview(view)

it's work

**Comment by dkcas11** [comment]
It sounds like you are doing something wrong.

When calling the show() method it presents the notification on the current ViewController. If you need to show a notification as soon as you have pushed or used a segue to a new VC, you need to call the show() method in that VC's viewDidAppear.

**Comment by adelbios** [comment]
i try but didn't work

**Comment by adelbios** [comment]
i mean i try pushed

**Comment by sshahidaslamm** [comment]
@adelbios I have fixed this problem.
Actually the problem is the CRnotification adding the view into root view and when you have Navigation controller or tab-bar controller this notification is not appearing on screen with following code:
`UIApplication.shared.keyWindow?.rootViewController?.view.addSubview(view)`

You should replace following with the above one to work
`UIApplication.shared.keyWindow?.addSubview(view)`

I think @dkcas11 you should have to update this in library as well.

**Comment by adelbios** [comment]
oK thanks but i fix it before 5 days

**Comment by dkcas11** [comment]
@adelbios @sshahidaslamm 

The problem doesn't lie with the way the view is presented.

The UIApplication object holds a list of UIWindows which have a UIViewController (their "parent"). So, in order to add something, you go to the ViewController and fetch it's view and add whatever you like there. Adding it to the UIWindow itself may be dangerous and this ensures that the view actually _is_ there.

I just tested this from the example project, where i added a NavigationController to the ViewController class, a button to the View, made a new UIViewController class and added a segue to this, from the button. In the newly added class, i ran the `show()` method from `viewDidAppear`... Worked perfectly fine. I also just ran the pushViewController directly when the button was pushed (which is the same as the segue does) and it also worked as intended. 

Clearly, something is wrong with how you do it, adelbios. Could you provide me with the code of how you do this? And possibly a short outline of your setup.

Just to show you my code, here is the PushViewController class i made:


```
class PushViewController: UIViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
	}
	
	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		
		CRNotifications.showNotification(type: .success, title: "Pushed through!", message: "I'm right here.", dismissDelay: 3)
	}	

}
```


And the execution of my push, which is as trivial as it gets:
```	
@IBAction func nextViewControllerButton(_ sender: Any) {
	navigationController?.pushViewController(PushViewController(), animated: true)
}
```

**Comment by adelbios** [comment]
i wanna contact you... give me u're Email
