### ISSUE TITLE
Enhancement request - show more then 2 lines of text

### ISSUE THREAD

**Issue by saldous** [dkcas11/CRNotifications#6]
Love this, but would like to be able to show a larger box with more lines of text for some notifications. Can you modify it so the box resizes automatically based on the length of the message text, please?

**Comment by dkcas11** [comment]
I can try and see what i can do. 

Essentially if you should need to show a lot of information, in a view like this then that should be handled by some sort of alert instead. Usually when you need to inform the user with a lot of information it is somewhat important and a notification at the top isn't expressing importance.

**Comment by daemelchi** [comment]
I second this - I have 1 error message that wraps to a 3rd line on the non-plus devices. I'd change the error message accordingly in the app, but it's sent from the server. Thank you!

**Comment by dkcas11** [comment]
@daemelchi What is the message that doesn't fit? 

I still stand by the design and the intended use. If there is a lot of information, an alert is more suited since more information in the majority of cases also means importance to the user and that the user's attention is required. Therefore it is not well suited to hide this in a notification which is not meant to be a primary communication channel.
So having more than two lines of text will take up too much screen space and be annoying to the user. Apple for once doesn't do this either and the text is then truncated for the user to tap on the notification, to know exactly what that notification is about (something that is already doable with this library).

However, one solution might be to make the font size smaller in order to accommodate this need. This is kind of a last resort as you shouldn't need to dynamically need to change a font size. This breaks a design and is confusing to the user.

**Comment by saldous** [comment]
I agree.
